FOOD_KNOWLEDGE_BASE = {
    "apple": {
        "name_cn": "苹果",
        "calories_per_100g": 52,
        "typical_weight": 180,
        "typical_calories": 95,
        "category": "水果",
        "prompts": ["apple", "red apple", "green apple", "a photo of an apple", "fresh apple fruit"],
    },
    "banana": {
        "name_cn": "香蕉",
        "calories_per_100g": 89,
        "typical_weight": 120,
        "typical_calories": 105,
        "category": "水果",
        "prompts": ["banana", "yellow banana", "a photo of a banana", "fresh banana fruit"],
    },
    "bread": {
        "name_cn": "面包",
        "calories_per_100g": 265,
        "typical_weight": 80,
        "typical_calories": 212,
        "category": "主食",
        "prompts": ["bread", "white bread", "a slice of bread", "loaf of bread", "bread slice"],
    },
    "carrot": {
        "name_cn": "胡萝卜",
        "calories_per_100g": 41,
        "typical_weight": 70,
        "typical_calories": 29,
        "category": "蔬菜",
        "prompts": ["carrot", "orange carrot", "a photo of a carrot", "fresh carrot vegetable"],
    },
    "cheese": {
        "name_cn": "奶酪",
        "calories_per_100g": 402,
        "typical_weight": 30,
        "typical_calories": 120,
        "category": "乳制品",
        "prompts": ["cheese", "cheddar cheese", "a piece of cheese", "cheese block"],
    },
    "chicken": {
        "name_cn": "鸡肉",
        "calories_per_100g": 239,
        "typical_weight": 150,
        "typical_calories": 358,
        "category": "肉类",
        "prompts": ["chicken", "cooked chicken", "roast chicken", "chicken breast", "grilled chicken"],
    },
    "egg": {
        "name_cn": "鸡蛋",
        "calories_per_100g": 155,
        "typical_weight": 50,
        "typical_calories": 78,
        "category": "蛋类",
        "prompts": ["egg", "boiled egg", "fried egg", "a photo of an egg", "chicken egg"],
    },
    "fish": {
        "name_cn": "鱼",
        "calories_per_100g": 165,
        "typical_weight": 200,
        "typical_calories": 330,
        "category": "海鲜",
        "prompts": ["fish", "cooked fish", "grilled fish", "a photo of fish dish", "fish fillet"],
    },
    "hamburger": {
        "name_cn": "汉堡",
        "calories_per_100g": 295,
        "typical_weight": 220,
        "typical_calories": 650,
        "category": "快餐",
        "prompts": ["hamburger", "burger", "cheeseburger", "a photo of a hamburger", "fast food burger"],
    },
    "ice_cream": {
        "name_cn": "冰淇淋",
        "calories_per_100g": 207,
        "typical_weight": 100,
        "typical_calories": 207,
        "category": "甜品",
        "prompts": ["ice cream", "vanilla ice cream", "a photo of ice cream", "ice cream cone"],
    },
    "pizza": {
        "name_cn": "披萨",
        "calories_per_100g": 266,
        "typical_weight": 300,
        "typical_calories": 798,
        "category": "快餐",
        "prompts": ["pizza", "cheese pizza", "pepperoni pizza", "a photo of a pizza", "italian pizza"],
    },
    "rice": {
        "name_cn": "米饭",
        "calories_per_100g": 130,
        "typical_weight": 200,
        "typical_calories": 260,
        "category": "主食",
        "prompts": ["rice", "white rice", "steamed rice", "a bowl of rice", "cooked rice"],
    },
    "salad": {
        "name_cn": "沙拉",
        "calories_per_100g": 85,
        "typical_weight": 250,
        "typical_calories": 212,
        "category": "蔬菜",
        "prompts": ["salad", "green salad", "vegetable salad", "a bowl of salad", "fresh salad"],
    },
    "sandwich": {
        "name_cn": "三明治",
        "calories_per_100g": 260,
        "typical_weight": 180,
        "typical_calories": 468,
        "category": "快餐",
        "prompts": ["sandwich", "ham sandwich", "a photo of a sandwich", "club sandwich"],
    },
    "soup": {
        "name_cn": "汤",
        "calories_per_100g": 65,
        "typical_weight": 300,
        "typical_calories": 195,
        "category": "汤品",
        "prompts": ["soup", "vegetable soup", "a bowl of soup", "tomato soup", "chicken soup"],
    },
    "steak": {
        "name_cn": "牛排",
        "calories_per_100g": 271,
        "typical_weight": 250,
        "typical_calories": 678,
        "category": "肉类",
        "prompts": ["steak", "beef steak", "grilled steak", "a photo of a steak", "cooked steak"],
    },
    "pasta": {
        "name_cn": "意大利面",
        "calories_per_100g": 158,
        "typical_weight": 250,
        "typical_calories": 395,
        "category": "主食",
        "prompts": ["pasta", "spaghetti", "a plate of pasta", "italian pasta", "noodles pasta"],
    },
    "potato": {
        "name_cn": "土豆",
        "calories_per_100g": 77,
        "typical_weight": 150,
        "typical_calories": 116,
        "category": "蔬菜",
        "prompts": ["potato", "baked potato", "a photo of a potato", "fresh potato"],
    },
    "tomato": {
        "name_cn": "番茄",
        "calories_per_100g": 18,
        "typical_weight": 120,
        "typical_calories": 22,
        "category": "蔬菜",
        "prompts": ["tomato", "red tomato", "a photo of a tomato", "fresh tomato vegetable"],
    },
    "cucumber": {
        "name_cn": "黄瓜",
        "calories_per_100g": 16,
        "typical_weight": 150,
        "typical_calories": 24,
        "category": "蔬菜",
        "prompts": ["cucumber", "green cucumber", "a photo of a cucumber", "fresh cucumber"],
    },
    "broccoli": {
        "name_cn": "西兰花",
        "calories_per_100g": 34,
        "typical_weight": 100,
        "typical_calories": 34,
        "category": "蔬菜",
        "prompts": ["broccoli", "green broccoli", "a photo of broccoli", "steamed broccoli"],
    },
    "beef": {
        "name_cn": "牛肉",
        "calories_per_100g": 250,
        "typical_weight": 150,
        "typical_calories": 375,
        "category": "肉类",
        "prompts": ["beef", "cooked beef", "a photo of beef meat", "red meat beef"],
    },
    "pork": {
        "name_cn": "猪肉",
        "calories_per_100g": 242,
        "typical_weight": 150,
        "typical_calories": 363,
        "category": "肉类",
        "prompts": ["pork", "cooked pork", "a photo of pork meat", "roasted pork"],
    },
    "shrimp": {
        "name_cn": "虾",
        "calories_per_100g": 99,
        "typical_weight": 100,
        "typical_calories": 99,
        "category": "海鲜",
        "prompts": ["shrimp", "cooked shrimp", "a photo of shrimp", "prawn", "grilled shrimp"],
    },
    "sushi": {
        "name_cn": "寿司",
        "calories_per_100g": 145,
        "typical_weight": 200,
        "typical_calories": 290,
        "category": "日料",
        "prompts": ["sushi", "japanese sushi", "a photo of sushi", "salmon sushi roll"],
    },
    "tofu": {
        "name_cn": "豆腐",
        "calories_per_100g": 76,
        "typical_weight": 150,
        "typical_calories": 114,
        "category": "豆制品",
        "prompts": ["tofu", "silken tofu", "a photo of tofu", "bean curd"],
    },
    "yogurt": {
        "name_cn": "酸奶",
        "calories_per_100g": 59,
        "typical_weight": 150,
        "typical_calories": 88,
        "category": "乳制品",
        "prompts": ["yogurt", "greek yogurt", "a photo of yogurt", "yoghurt"],
    },
    "milk": {
        "name_cn": "牛奶",
        "calories_per_100g": 42,
        "typical_weight": 250,
        "typical_calories": 105,
        "category": "乳制品",
        "prompts": ["milk", "a glass of milk", "white milk", "dairy milk"],
    },
    "chocolate": {
        "name_cn": "巧克力",
        "calories_per_100g": 546,
        "typical_weight": 40,
        "typical_calories": 218,
        "category": "甜品",
        "prompts": ["chocolate", "dark chocolate", "a photo of chocolate", "chocolate bar"],
    },
    "cake": {
        "name_cn": "蛋糕",
        "calories_per_100g": 350,
        "typical_weight": 100,
        "typical_calories": 350,
        "category": "甜品",
        "prompts": ["cake", "chocolate cake", "a photo of a cake", "birthday cake", "cream cake"],
    },
    "donut": {
        "name_cn": "甜甜圈",
        "calories_per_100g": 452,
        "typical_weight": 60,
        "typical_calories": 271,
        "category": "甜品",
        "prompts": ["donut", "doughnut", "a photo of a donut", "glazed donut"],
    },
    "pancake": {
        "name_cn": "煎饼",
        "calories_per_100g": 227,
        "typical_weight": 100,
        "typical_calories": 227,
        "category": "早餐",
        "prompts": ["pancake", "a stack of pancakes", "a photo of pancakes", "breakfast pancake"],
    },
    "french_fries": {
        "name_cn": "薯条",
        "calories_per_100g": 312,
        "typical_weight": 120,
        "typical_calories": 374,
        "category": "快餐",
        "prompts": ["french fries", "fries", "a photo of french fries", "fried potato chips", "fast food fries"],
    },
    "popcorn": {
        "name_cn": "爆米花",
        "calories_per_100g": 375,
        "typical_weight": 50,
        "typical_calories": 187,
        "category": "零食",
        "prompts": ["popcorn", "a bucket of popcorn", "a photo of popcorn", "movie popcorn"],
    },
    "strawberry": {
        "name_cn": "草莓",
        "calories_per_100g": 32,
        "typical_weight": 100,
        "typical_calories": 32,
        "category": "水果",
        "prompts": ["strawberry", "red strawberry", "a photo of strawberries", "fresh strawberry fruit"],
    },
    "grape": {
        "name_cn": "葡萄",
        "calories_per_100g": 69,
        "typical_weight": 100,
        "typical_calories": 69,
        "category": "水果",
        "prompts": ["grape", "purple grape", "a photo of grapes", "fresh grape fruit"],
    },
    "watermelon": {
        "name_cn": "西瓜",
        "calories_per_100g": 30,
        "typical_weight": 500,
        "typical_calories": 150,
        "category": "水果",
        "prompts": ["watermelon", "a photo of watermelon", "fresh watermelon fruit", "slice of watermelon"],
    },
    "orange": {
        "name_cn": "橙子",
        "calories_per_100g": 47,
        "typical_weight": 140,
        "typical_calories": 66,
        "category": "水果",
        "prompts": ["orange", "a photo of an orange", "fresh orange fruit", "citrus orange"],
    },
    "avocado": {
        "name_cn": "牛油果",
        "calories_per_100g": 160,
        "typical_weight": 150,
        "typical_calories": 240,
        "category": "水果",
        "prompts": ["avocado", "a photo of an avocado", "fresh avocado", "green avocado"],
    },
    "nuts": {
        "name_cn": "坚果",
        "calories_per_100g": 607,
        "typical_weight": 30,
        "typical_calories": 182,
        "category": "零食",
        "prompts": ["nuts", "mixed nuts", "a photo of nuts", "almonds and walnuts"],
    },
    "dumpling": {
        "name_cn": "饺子",
        "calories_per_100g": 170,
        "typical_weight": 200,
        "typical_calories": 340,
        "category": "中餐",
        "prompts": ["dumpling", "chinese dumpling", "a photo of dumplings", "jiaozi", "steamed dumplings"],
    },
    "noodle": {
        "name_cn": "面条",
        "calories_per_100g": 138,
        "typical_weight": 250,
        "typical_calories": 345,
        "category": "主食",
        "prompts": ["noodles", "a bowl of noodles", "chinese noodles", "ramen noodles", "pasta noodles"],
    },
    "croissant": {
        "name_cn": "可颂",
        "calories_per_100g": 406,
        "typical_weight": 60,
        "typical_calories": 244,
        "category": "烘焙",
        "prompts": ["croissant", "a photo of a croissant", "french croissant", "butter croissant"],
    },
    "muffin": {
        "name_cn": "马芬",
        "calories_per_100g": 320,
        "typical_weight": 70,
        "typical_calories": 224,
        "category": "烘焙",
        "prompts": ["muffin", "a photo of a muffin", "blueberry muffin", "cupcake muffin"],
    },
    "pie": {
        "name_cn": "派",
        "calories_per_100g": 260,
        "typical_weight": 120,
        "typical_calories": 312,
        "category": "甜品",
        "prompts": ["pie", "apple pie", "a photo of a pie", "fruit pie"],
    },
    "cookie": {
        "name_cn": "曲奇",
        "calories_per_100g": 488,
        "typical_weight": 30,
        "typical_calories": 146,
        "category": "零食",
        "prompts": ["cookie", "chocolate chip cookie", "a photo of cookies", "biscuit cookie"],
    },
    "cheese_cake": {
        "name_cn": "芝士蛋糕",
        "calories_per_100g": 321,
        "typical_weight": 100,
        "typical_calories": 321,
        "category": "甜品",
        "prompts": ["cheesecake", "a photo of a cheesecake", "cream cheese cake", "new york cheesecake"],
    },
    "corn": {
        "name_cn": "玉米",
        "calories_per_100g": 86,
        "typical_weight": 150,
        "typical_calories": 129,
        "category": "蔬菜",
        "prompts": ["corn", "sweet corn", "a photo of corn", "corn on the cob"],
    },
    "onion": {
        "name_cn": "洋葱",
        "calories_per_100g": 40,
        "typical_weight": 100,
        "typical_calories": 40,
        "category": "蔬菜",
        "prompts": ["onion", "a photo of an onion", "red onion", "white onion"],
    },
    "cauliflower": {
        "name_cn": "花椰菜",
        "calories_per_100g": 25,
        "typical_weight": 100,
        "typical_calories": 25,
        "category": "蔬菜",
        "prompts": ["cauliflower", "a photo of cauliflower", "white cauliflower"],
    },
    "cabbage": {
        "name_cn": "卷心菜",
        "calories_per_100g": 25,
        "typical_weight": 150,
        "typical_calories": 38,
        "category": "蔬菜",
        "prompts": ["cabbage", "green cabbage", "a photo of cabbage", "head of cabbage"],
    },
    "spinach": {
        "name_cn": "菠菜",
        "calories_per_100g": 23,
        "typical_weight": 80,
        "typical_calories": 18,
        "category": "蔬菜",
        "prompts": ["spinach", "fresh spinach", "a photo of spinach", "green spinach leaves"],
    },
    "beans": {
        "name_cn": "豆子",
        "calories_per_100g": 127,
        "typical_weight": 100,
        "typical_calories": 127,
        "category": "豆类",
        "prompts": ["beans", "green beans", "a photo of beans", "red kidney beans"],
    },
    "peas": {
        "name_cn": "豌豆",
        "calories_per_100g": 81,
        "typical_weight": 50,
        "typical_calories": 41,
        "category": "豆类",
        "prompts": ["peas", "green peas", "a photo of peas", "fresh garden peas"],
    },
    "mushroom": {
        "name_cn": "蘑菇",
        "calories_per_100g": 22,
        "typical_weight": 80,
        "typical_calories": 18,
        "category": "菌类",
        "prompts": ["mushroom", "white mushroom", "a photo of mushrooms", "button mushrooms"],
    },
    "garlic": {
        "name_cn": "大蒜",
        "calories_per_100g": 149,
        "typical_weight": 10,
        "typical_calories": 15,
        "category": "调味",
        "prompts": ["garlic", "a photo of garlic", "garlic cloves", "fresh garlic"],
    },
    "olive": {
        "name_cn": "橄榄",
        "calories_per_100g": 115,
        "typical_weight": 15,
        "typical_calories": 17,
        "category": "零食",
        "prompts": ["olive", "black olive", "a photo of olives", "green olive"],
    },
    "lamb": {
        "name_cn": "羊肉",
        "calories_per_100g": 294,
        "typical_weight": 150,
        "typical_calories": 441,
        "category": "肉类",
        "prompts": ["lamb", "lamb chops", "a photo of lamb meat", "roasted lamb"],
    },
    "lobster": {
        "name_cn": "龙虾",
        "calories_per_100g": 90,
        "typical_weight": 200,
        "typical_calories": 180,
        "category": "海鲜",
        "prompts": ["lobster", "a photo of a lobster", "cooked lobster", "red lobster"],
    },
    "crab": {
        "name_cn": "螃蟹",
        "calories_per_100g": 97,
        "typical_weight": 150,
        "typical_calories": 146,
        "category": "海鲜",
        "prompts": ["crab", "a photo of a crab", "cooked crab", "seafood crab"],
    },
    "rice_cake": {
        "name_cn": "年糕",
        "calories_per_100g": 190,
        "typical_weight": 100,
        "typical_calories": 190,
        "category": "中餐",
        "prompts": ["rice cake", "korean rice cake", "a photo of rice cake", "tteok"],
    },
    "bread_roll": {
        "name_cn": "餐包",
        "calories_per_100g": 280,
        "typical_weight": 50,
        "typical_calories": 140,
        "category": "烘焙",
        "prompts": ["bread roll", "dinner roll", "a photo of bread rolls", "soft roll"],
    },
    "waffle": {
        "name_cn": "华夫饼",
        "calories_per_100g": 291,
        "typical_weight": 80,
        "typical_calories": 233,
        "category": "早餐",
        "prompts": ["waffle", "a photo of a waffle", "belgian waffle", "breakfast waffle"],
    },
    "seeds": {
        "name_cn": "种子",
        "calories_per_100g": 550,
        "typical_weight": 20,
        "typical_calories": 110,
        "category": "零食",
        "prompts": ["seeds", "sunflower seeds", "a photo of seeds", "pumpkin seeds"],
    },
}


def get_food_list():
    return list(FOOD_KNOWLEDGE_BASE.keys())


def get_food_info(food_key):
    return FOOD_KNOWLEDGE_BASE.get(food_key, {})


def get_prompts_for_all_foods():
    prompts = []
    food_keys = []
    for key, info in FOOD_KNOWLEDGE_BASE.items():
        for p in info["prompts"]:
            prompts.append(p)
            food_keys.append(key)
    return prompts, food_keys


def estimate_calories(food_key, confidence=1.0):
    info = FOOD_KNOWLEDGE_BASE.get(food_key)
    if info is None:
        return {"calories": 0, "weight": 0}
    
    base_cal = info["typical_calories"]
    base_weight = info["typical_weight"]
    
    variation = (1.0 - confidence) * 0.3
    import random
    random.seed(hash(food_key) % 10000)
    factor = 1.0 + (random.random() - 0.5) * variation
    
    return {
        "calories": base_cal * factor,
        "weight": base_weight * factor,
    }
