IMAGENET_FOOD_MAPPING = {
    "apple": ["apple", "Granny Smith"],
    "banana": ["banana"],
    "strawberry": ["strawberry"],
    "orange": ["orange"],
    "grape": ["grape", "grocery store"],
    "watermelon": ["watermelon"],
    "pineapple": ["pineapple", "ananas"],
    "corn": ["corn", "ear of corn"],
    "carrot": ["carrot", "mashed carrot"],
    "broccoli": ["broccoli"],
    "cauliflower": ["cauliflower"],
    "cucumber": ["cucumber", "cucumber slice"],
    "tomato": ["tomato"],
    "potato": ["potato", "mashed potato"],
    "mushroom": ["mushroom", "bolete"],
    "onion": ["onion", "yellow onion"],
    "garlic": ["garlic"],
    "cabbage": ["cabbage", "head of cabbage"],
    "spinach": ["spinach"],
    "peas": ["pea", "green pea"],
    "beans": ["bean", "green bean", "kidney bean"],
    "rice": ["rice", "rice bowl"],
    "bread": ["bread", "bagel", "pretzel", "baguette"],
    "bread_roll": ["dinner roll", "roll"],
    "croissant": ["croissant"],
    "donut": ["doughnut", "donut"],
    "muffin": ["muffin", "cup"],
    "pancake": ["pancake", "hotcake"],
    "waffle": ["waffle", "waffle iron"],
    "hamburger": ["hamburger", "cheeseburger", "Big Mac"],
    "pizza": ["pizza", "pizza pie"],
    "hotdog": ["hot dog", "frankfurter"],
    "sandwich": ["sandwich", "submarine sandwich", "hoagie"],
    "french_fries": ["French loaf", "french fry", "hot pot"],
    "popcorn": ["popcorn", "popcorn bucket"],
    "noodle": ["noodle", "spaghetti", "pasta"],
    "pasta": ["spaghetti", "pasta", "carbonara"],
    "dumpling": ["dumpling", "pot sticker"],
    "sushi": ["sushi", "sushi roll"],
    "rice_cake": ["rice cake"],
    "soup": ["soup", "consomme", "hot pot", "soup bowl"],
    "salad": ["salad", "green salad", "caesar salad"],
    "steak": ["steak", "filet mignon"],
    "beef": ["beef", "roast beef", "meatloaf"],
    "pork": ["pork", "ham", "bacon"],
    "chicken": ["chicken", "roast chicken", "hen"],
    "lamb": ["lamb", "lamb chop"],
    "fish": ["fish", "goldfish", "tench"],
    "shrimp": ["shrimp", "prawn", "crayfish"],
    "crab": ["crab", "Dungeness crab", "rock crab"],
    "lobster": ["lobster", "spiny lobster"],
    "egg": ["egg", "boiled egg"],
    "cheese": ["cheese", "cheddar"],
    "milk": ["milk", "milk bottle"],
    "yogurt": ["yogurt", "yoghurt"],
    "butter": ["butter"],
    "ice_cream": ["ice cream", "ice cream cone", "vanilla ice cream"],
    "cake": ["cake", "chocolate cake", "fountain"],
    "cheese_cake": ["cheesecake"],
    "pie": ["pie", "potpie"],
    "cookie": ["cookie", "chocolate chip cookie"],
    "chocolate": ["chocolate", "candy bar"],
    "candy": ["candy", "lollipop"],
    "nuts": ["nut", "acorn", "walnut"],
    "seeds": ["seed", "sunflower seed"],
    "olive": ["olive"],
    "avocado": ["avocado", "guacamole"],
    "tofu": ["tofu", "bean curd"],
    "honey": ["honey", "honeycomb"],
    "jam": ["jam", "jelly jar"],
    "sauce": ["sauce", "ketchup", "mayonnaise"],
    "coffee": ["coffee", "coffee mug", "espresso"],
    "tea": ["tea", "teacup"],
    "juice": ["juice", "orange juice"],
    "wine": ["wine", "wine bottle", "red wine"],
    "beer": ["beer", "beer bottle", "beer glass"],
    "cocktail": ["cocktail", "martini"],
}


FOOD_CATEGORY_HIERARCHY = {
    "水果": ["apple", "banana", "strawberry", "orange", "grape", "watermelon", "pineapple", "avocado"],
    "蔬菜": ["carrot", "broccoli", "cauliflower", "cucumber", "tomato", "potato", "corn", "mushroom", 
             "onion", "garlic", "cabbage", "spinach", "peas", "beans", "olive"],
    "肉类": ["steak", "beef", "pork", "chicken", "lamb"],
    "海鲜": ["fish", "shrimp", "crab", "lobster"],
    "主食": ["rice", "bread", "bread_roll", "noodle", "pasta", "dumpling", "sushi", "rice_cake", "pancake", "waffle"],
    "快餐": ["hamburger", "pizza", "hotdog", "sandwich", "french_fries"],
    "甜品": ["ice_cream", "cake", "cheese_cake", "pie", "cookie", "chocolate", "candy", "donut", "muffin", "croissant"],
    "零食": ["popcorn", "nuts", "seeds", "chips"],
    "乳制品": ["cheese", "milk", "yogurt", "butter"],
    "豆制品": ["tofu"],
    "蛋类": ["egg"],
    "汤品": ["soup"],
    "烘焙": ["bread", "bread_roll", "croissant", "muffin", "donut"],
    "早餐": ["pancake", "waffle", "bread", "egg"],
    "中餐": ["dumpling", "rice_cake", "noodle", "rice"],
    "日料": ["sushi"],
}
